# Application of Bootstrap samples in Random Forest

In [1]:
import numpy as np
import pandas as pd
import random
from sklearn.datasets import load_boston
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor

 <li> Load the boston house dataset </li>

In [2]:
boston = load_boston()
x=boston.data #independent variables
y=boston.target #target variable

In [3]:
x.shape

(506, 13)

Task: 1

Step 1 Creating samples: Randomly create 30 samples from the whole boston data points.

    Creating each sample: Consider any random 303(60% of 506) data points from whole data set and then replicate any 203 points from the sampled points
    Ex: For better understanding of this procedure lets check this examples, assume we have 10 data points [1,2,3,4,5,6,7,8,9,10], first we take 6 data points randomly consider we have selected [4, 5, 7, 8, 9, 3] now we will replciate 4 points from [4, 5, 7, 8, 9, 3], consder they are [5, 8, 3,7] so our final sample will be [4, 5, 7, 8, 9, 3, 5, 8, 3,7]
    we create 30 samples like this
    Note that as a part of the Bagging when you are taking the random samples make sure each of the sample will have different set of columns
    Ex: assume we have 10 columns for the first sample we will select [3, 4, 5, 9, 1, 2] and for the second sample [7, 9, 1, 4, 5, 6, 2] and so on...
    Make sure each sample will have atleast 3 feautres/columns/attributes
Step 2 Building High Variance Models on each of the sample and finding train MSE value: Build a DecisionTreeRegressor on each of the sample.

    Build a regression trees on each of 30 samples.
    computed the predicted values of each data point(506 data points) in your corpus.
    predicted house price of ith data point yipred=130∑30k=1(predicted value of xi with kth model).
    Now calculate the MSE=1506∑506i=1(yi−yipred)2.
 
 Step 3 Calculating the OOB score :

    Computed the predicted values of each data point(506 data points) in your corpus.
    Predicted house price of ith data point yipred=1k∑k= model which was buit on samples not included xi(predicted value of xi with kth model).
    Now calculate the OOBScore=1506∑506i=1(yi−yipred)2.

Task: 2

Computing CI of OOB Score and Train MSE


     Repeat Task 1 for 35 times, and for each iteration store the Train MSE and OOB score 

     After this we will have 35 Train MSE values and 35 OOB scores 
     using these 35 values (assume like a sample) find the confidence intravels of MSE and OOB Score 

     you need to report CI of MSE and CI of OOB Score 

     Note: Refer the Central_Limit_theorem.ipynb to check how to find the confidence intravel


Task: 3

Given a single query point predict the price of house.

Consider xq= [0.18,20.0,5.00,0.0,0.421,5.60,72.2,7.95,7.0,30.0,19.1,372.13,18.60] Predict the house price for this point as mentioned in the step 2 of Task 1. 

# Task: 1

In [4]:
x = pd.DataFrame(x)
y = pd.DataFrame(y)
sample_x =[]
sample_y=[]
x_data =[]

### Step 1 Creating samples: Randomly create 30 samples from the whole boston data points.

In [5]:
j = 1
for i in range(30):
    val = random.randint(3,12)
    temp1= x.sample(n=val,axis='columns',replace=False,random_state=j)
    x_data.append(np.array(temp1))
    s = np.array(temp1.sample(n=303,random_state=j))
    temp2 = y.sample(n=303,random_state=j)
    sample_x.append(s)
    sample_y.append(temp2)
    j = j+1
print(j)

31


In [6]:
print(x_data[12])

[[  6.575  296.       0.       4.09  ]
 [  6.421  242.       0.       4.9671]
 [  7.185  242.       0.       4.9671]
 ...
 [  6.976  273.       0.       2.1675]
 [  6.794  273.       0.       2.3889]
 [  6.03   273.       0.       2.505 ]]


Here i created two lists for storing 30 samples sample_x and y with same random state to select same rows also i have done the column wise sampling for x data set and appended both of them list and created list of arrays.

In [7]:
n=len(sample_x)
print(n)
print(len(sample_y))

30
30


In [8]:
print(len(sample_x[29]))
print(len(sample_x[29][0]))

303
6


In [9]:
print(sample_x[29][0:10])

[[8.52040e-01 4.00000e+00 2.10000e+01 3.07000e+02 8.92000e+01 0.00000e+00]
 [2.20511e+01 2.40000e+01 2.02000e+01 6.66000e+02 9.24000e+01 0.00000e+00]
 [2.11610e-01 5.00000e+00 2.09000e+01 3.84000e+02 8.74000e+01 0.00000e+00]
 [6.64200e-02 5.00000e+00 1.66000e+01 2.96000e+02 7.44000e+01 0.00000e+00]
 [1.23247e+00 4.00000e+00 2.10000e+01 3.07000e+02 9.17000e+01 0.00000e+00]
 [1.35472e+00 4.00000e+00 2.10000e+01 3.07000e+02 1.00000e+02 0.00000e+00]
 [1.96500e-02 1.00000e+00 1.82000e+01 2.41000e+02 3.15000e+01 8.00000e+01]
 [6.12900e-02 5.00000e+00 1.49000e+01 2.16000e+02 4.97000e+01 2.00000e+01]
 [8.79212e+00 2.40000e+01 2.02000e+01 6.66000e+02 7.06000e+01 0.00000e+00]
 [1.48660e-01 5.00000e+00 2.09000e+01 3.84000e+02 7.99000e+01 0.00000e+00]]


In [10]:
print(len(sample_x))
print(len(sample_y[10]))

30
303


In [11]:
sample_lst_x =[]
sample_lst_y =[]

In [12]:
for i in range(n):
    temp1_x = pd.DataFrame(sample_x[i])
    temp1_y = pd.DataFrame(sample_y[i])
    temp2_x = temp1_x.sample(n=203,random_state=9)  #subset of each sample with 203 data pts with a particular random state
    temp2_y = temp1_y.sample(n=203,random_state=9)
    temp3_x = temp1_x
    temp3_y = temp1_y
    temp3_x = np.array(temp3_x.append(temp2_x))   #appended the subset to the same sample to create 506 data pts
    temp3_y = np.array(temp3_y.append(temp2_y))
    sample_lst_x.append(temp3_x)
    sample_lst_y.append(temp3_y)
    

In [13]:
print(len(sample_lst_x[29][0]))
print(len(sample_lst_x[29]))
print(len(sample_lst_y[29][0]))
print(len(sample_lst_y[29]))

6
506
1
506


In [14]:
print(type(sample_lst_x[29]))
print(type(sample_lst_y[29]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


So i have created 30 random samples and resampled them with 203 data points and added them back to samples, and the sampled columns with replace as False just to get unique features every time

### Step 2 Building High Variance Models on each of the sample and finding train MSE value:

In [15]:
samples_y_pred =[]

In [16]:
j=1
for i in range(30):
    tree = DecisionTreeRegressor()
    tree_reg =tree.fit(sample_lst_x[i],sample_lst_y[i])
    x_data = x.sample(n=len(sample_lst_x[i][0]),axis='columns',replace=False,random_state=j)
    y_pred = tree_reg.predict(x_data)
    samples_y_pred.append(y_pred)
    j+=1
    

In [17]:
print(len(samples_y_pred[0]))

506


so here i'm getting y_pred value for easch sample

In [18]:
samples_y_pred_df = pd.DataFrame(samples_y_pred)

In [19]:
samples_y_pred_df.head(30)

0          1          2     3     4     5     6     7          8     9    \
0   24.0  21.200000  32.000000  32.0  36.2  28.7  22.9  16.6  16.500000  18.9   
1   28.4  21.600000  34.700000  33.4  36.2  28.7  22.9  27.1  23.100000  18.9   
2   35.1  21.200000  33.100000  33.4  36.2  28.7  22.9  15.0  18.500000  16.0   
3   32.7  21.600000  32.000000  50.0  36.1  31.1  22.9  18.7  16.500000  18.7   
4   24.0  21.600000  34.700000  33.4  36.2  28.4  22.9  16.6  14.400000  18.9   
5   24.0  18.640000  34.700000  28.7  36.2  28.7  22.9  18.9  16.500000  16.5   
6   36.2  23.900000  34.700000  33.4  23.6  23.1  18.9  27.1  16.500000  18.9   
7   24.0  21.600000  21.600000  33.4  36.2  28.7  22.7  16.5  16.500000  24.8   
8   22.6  34.700000  34.700000  33.4  36.2  28.7  22.9  27.1  16.500000  18.9   
9   24.0  21.600000  34.700000  28.7  23.9  28.7  22.9  27.1  15.000000  16.6   
10  24.0  20.300000  34.700000  33.4  36.2  24.4  20.5  27.1  21.621429  18.9   
11  24.0  21.600000  36.200000  33.4  36.2  28.7  22.9  27.1  16.500000  18.9   
12  24.0  23.900000  34.700000  36.2  36.2  28.7  21.7  27.1  17.400000  18.9   
13  29.1  21.600000  33.400000  33.4  33.4  28.7  22.9  27.1  16.500000  18.8   
14  28.7  20.600000  34.700000  33.4  36.2  28.7  22.9  27.1  16.500000  18.9   
15  24.0  21.600000  34.700000  33.4  28.7  28.7  23.0  27.1  21.700000  18.9   
16  24.0  28.100000  43.500000  33.4  36.2  22.9  22.9  21.7  23.700000  18.9   
17  24.0  21.600000  34.700000  33.4  36.2  36.1  22.9  27.1  16.500000  18.9   
18  45.4  21.600000  34.700000  50.0  46.0  34.7  22.9  27.1  16.500000  21.7   
19  24.0  21.600000  34.700000  32.9  29.0  28.7  18.7  27.1  16.500000  18.9   
20  24.4  24.200000  34.700000  23.6  36.2  24.2  22.9  27.1  19.300000  18.9   
21  34.9  21.600000  34.700000  33.4  36.2  36.2  22.2  21.7  21.700000  21.7   
22  29.4  23.900000  34.700000  33.4  32.9  28.7  23.2  15.0  16.500000  14.8   
23  24.0  20.600000  34.700000  33.4  37.2  28.7  22.9  21.5  14.600000  16.6   
24  24.0  21.600000  43.800000  33.4  36.2  36.2  22.9  27.1  13.400000  18.9   
25  24.0  25.966667  25.966667  28.7  28.7  28.7  23.9  18.9  18.900000  18.9   
26  31.1  22.000000  48.300000  33.4  36.5  28.7  22.9  27.1  16.500000  18.9   
27  24.0  21.600000  31.200000  50.0  36.2  36.1  22.9  27.1  16.500000  18.9   
28  41.3  21.600000  34.700000  44.0  28.0  28.7  22.9  16.6  16.500000  21.7   
29  24.0  21.600000  34.700000  33.4  36.1  33.4  22.9  27.1  16.500000  18.5   

    ...         496        497        498   499        500   501   502   503  \
0   ...   19.300000  18.300000  21.200000  18.8  18.300000  22.4  20.6  23.9   
1   ...   19.700000  24.500000  24.500000  17.5  24.500000  22.0  20.6  29.8   
2   ...   19.700000  18.300000  16.800000  17.5  16.800000  28.4  20.6  23.9   
3   ...   19.700000  18.300000  22.200000  17.5  18.600000  22.4  20.6  27.0   
4   ...   19.700000  20.800000  19.200000  17.5  16.800000  22.4  20.6  23.9   
5   ...   21.085714  21.085714  21.085714  18.8  21.085714  22.4  19.9  19.9   
6   ...   16.500000  18.300000  21.200000  17.5  16.800000  22.6  23.1  23.9   
7   ...   19.700000  18.900000  16.800000  17.5  16.800000  27.5  27.5  19.5   
8   ...   19.700000  19.700000  21.200000  17.5  16.800000  20.1  20.6  23.9   
9   ...   26.500000  18.300000  22.800000  22.8  22.800000  22.4  22.0  23.9   
10  ...   19.700000  18.300000  20.500000  17.5  19.200000  22.4  20.3  23.9   
11  ...   19.700000  20.000000  24.500000  17.5  22.000000  22.4  20.6  26.7   
12  ...   19.700000  18.300000  21.200000  23.1  16.800000  27.5  22.2  30.7   
13  ...   19.400000  20.000000  21.200000  17.5  11.900000  22.0  20.6  23.6   
14  ...   19.100000  18.300000  21.200000  17.5  16.800000  26.5  11.9  23.9   
15  ...   19.700000  18.300000  18.900000  17.5  16.200000  22.4  20.6  19.5   
16  ...   19.700000  18.300000  21.200000  17.5  16.800000  22.4  11.9  23.9   
17  ...   19.700000  19.600000  21.200000  17.5  16.8

So here it shows all the predicted values for each data point for all the 30 samples

In [20]:
y_pred = samples_y_pred_df.sum(axis='rows')/30

In [21]:
print(y_pred.shape)
print(y_pred)

(506,)
0      27.576667
1      22.493556
2      34.678889
3      34.646667
4      34.516667
5      29.446667
6      22.523333
7      23.516667
8      17.460714
9      18.886667
10     16.946667
11     19.356667
12     21.380000
13     20.406667
14     18.630000
15     20.620000
16     22.266667
17     17.673333
18     21.053333
19     19.103333
20     14.400000
21     18.673333
22     15.716667
23     14.863333
24     15.458333
25     14.463333
26     17.080000
27     15.150000
28     18.540000
29     19.570000
         ...    
476    16.663333
477    12.440000
478    15.086667
479    21.400000
480    21.976857
481    26.516667
482    26.190000
483    19.853333
484    20.283333
485    21.646667
486    19.066667
487    20.793333
488    14.560000
489     8.986667
490     9.440000
491    14.096667
492    19.570000
493    21.122857
494    22.839524
495    22.180000
496    19.632857
497    19.646190
498    21.032857
499    18.876667
500    18.176190
501    23.066667
502    20.143333
503    

In [22]:
y = np.array(y)
y_pred = np.array(y_pred)
print(y[0])

[24.]


In [26]:
sum =0
for i in range(506):
    sum += (y[i]-y_pred[i])**2
MSE = sum/506   

In [27]:
print(MSE)

[2.48114075]


### Step 3 Calculating the OOB score :

In [29]:
# k =[]

for j in range(1):
    sample = pd.DataFrame(sample_lst_x[j])
    print(x_data[j])
#     for i  in range(1):  
#         entry = np.array(x.iloc[i,:])
#         print(entry)
#         print(sample.iloc[i,:])
#         print(sample.index == 'entry')
        
# #     n= sample.shape[1]
#     a = entry.merge(sample)
#     print(a)
# #     for k in range(13):
# #          print(sample[k])
# # #         if (entry[k]==sample_lst_x[j][k]):
# # #             count+=1
# # #             if (count==n):
# # #                 return True
    
             
    

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: 0, Length: 506, dtype: float64


In [30]:
print(x_data)

          0    8     10
0    0.00632  1.0  15.3
1    0.02731  2.0  17.8
2    0.02729  2.0  17.8
3    0.03237  3.0  18.7
4    0.06905  3.0  18.7
..       ...  ...   ...
501  0.06263  1.0  21.0
502  0.04527  1.0  21.0
503  0.06076  1.0  21.0
504  0.10959  1.0  21.0
505  0.04741  1.0  21.0

[506 rows x 3 columns]


In [39]:
for i in range(1):
    sample = pd.DataFrame(sample_lst_x[0])
    print(sample.shape)
#     df = pd.merge(x,sample,on=['User','Movie'],how='left', indicator ='Exist')
    

(506, 4)


In [38]:
df

0    1      2     3   4   5   6   7   8   9  10  11  12      Exist
0     2.18  0.0  0.472  18.4 NaN NaN NaN NaN NaN NaN NaN NaN NaN  left_only
1     3.78  0.0  0.484  17.6 NaN NaN NaN NaN NaN NaN NaN NaN NaN  left_only
2     6.91  0.0  0.448  17.9 NaN NaN NaN NaN NaN NaN NaN NaN NaN  left_only
3     6.07  0.0  0.409  18.9 NaN NaN NaN NaN NaN NaN NaN NaN NaN  left_only
4    18.10  0.0  0.770  20.2 NaN NaN NaN NaN NaN NaN NaN NaN NaN  left_only
..     ...  ...    ...   ...  ..  ..  ..  ..  ..  ..  ..  ..  ..        ...
501   7.38  0.0  0.493  19.6 NaN NaN NaN NaN NaN NaN NaN NaN NaN  left_only
502  19.58  0.0  0.605  14.7 NaN NaN NaN NaN NaN NaN NaN NaN NaN  left_only
503  25.65  0.0  0.581  19.1 NaN NaN NaN NaN NaN NaN NaN NaN NaN  left_only
504   6.20  0.0  0.507  17.4 NaN NaN NaN NaN NaN NaN NaN NaN NaN  left_only
505   5.19  0.0  0.515  20.2 NaN NaN NaN NaN NaN NaN NaN NaN NaN  left_only

[506 rows x 14 columns]